; Listing generated by Microsoft (R) Optimizing Compiler Version 19.14.26430.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\sazhang\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
